### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.espertech.esper.common.internal.serde.DataInputOutputSerdeWCollation

### ISSUE THREAD

**Issue by yangguang760** [espertechinc/esper#132]
My program works well on esper common/compiler/runtime 8.0.0-beta1.
When updated to 8.0.0, it throws exception as follow:

```
Caused by: com.espertech.esper.runtime.client.EPDeployException: com/espertech/esper/common/internal/serde/DataInputOutputSerdeWCollation
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploy(Deployer.java:111)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deployFresh(Deployer.java:95)
	at com.espertech.esper.runtime.internal.kernel.service.EPDeploymentServiceImpl.deploy(EPDeploymentServiceImpl.java:83)
	at com.espertech.esper.runtime.internal.kernel.service.EPDeploymentServiceImpl.deploy(EPDeploymentServiceImpl.java:42)
	at com.yg.esper.EsperModule.installModule(EsperModule.scala:26)
	at com.yg.esper.EsperModule.installModule$(EsperModule.scala:22)
	at com.yg.actors.strategyEngine.BTEsperSE.installModule(BTEsperSE.scala:33)
	at com.yg.actors.strategyEngine.BTEsperSE.$anonfun$startEngine$8(BTEsperSE.scala:144)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:58)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:51)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at com.yg.actors.strategyEngine.BTEsperSE.startEngine(BTEsperSE.scala:143)
	at com.yg.actors.strategyEngine.BTEsperSE.<init>(BTEsperSE.scala:90)
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/espertech/esper/common/internal/serde/DataInputOutputSerdeWCollation
	at generated.StatementProvider_com46yg46ygtrader46position_genPositionByOpenOrder.initialize(StatementProvider_com46yg46ygtrader46position_genPositionByOpenOrder.java:27)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.initStatement(Deployer.java:674)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploySafe(Deployer.java:352)
	at com.espertech.esper.runtime.internal.kernel.service.Deployer.deploy(Deployer.java:107)
	... 30 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.espertech.esper.common.internal.serde.DataInputOutputSerdeWCollation
	at com.espertech.esper.common.internal.context.util.ByteArrayProvidingClassLoader.findClass(ByteArrayProvidingClassLoader.java:28)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 34 common frames omitted
```

genPositionByOpenOrder epl:
```
    @Name("genPositionByOpenOrder")
                              insert into Position
                              select
                              a.createdTime as tradeDate,
                              a.acctId as acctId,
                              a.portfolioId as portfolioId,
                              a.exchId as exchId,
                              a.currencyId as currencyId,
                              "future" as underlyingType,
                              a.symbol as symbol,
                              a.bsFlag as bsFlag,
                              a.hedgeFlag as hedgeFlag,
                              a.fproductId as fproductId,
                              0.0 as prePositionQty,
                              0.0 as currentPositionQty,
                              0.0 as prePositionUsableQty,
                              0.0 as currentPositionUsableQty,
                              0.0 as frozenQty,
                              case when a.bsFlag>0
                              then
                              a.orderQty*a.orderPrice*i.multiple*m.longByMoney+a.orderQty*m.longByQty
                              else
                              a.orderQty*a.orderPrice*i.multiple*m.shortByMoney+a.orderQty*m.shortByQty
                              end
                              as forzenAmount,
                              0.0 as openVolume,
                              0.0 as closeVolume,
                              0.0 as openAmount,
                              0.0 as closeAmount,
                              f.openByMoney*a.orderQty*a.orderPrice*i.multiple+f.openByQty*a.orderQty as frozenFee,
                              0.0 as fee,
                              0.0 as closeProfit,
                              0.0 as floatProfit,
                              "tempTradingDay" as tradingDay,
                              0.0 as avgCost,
                              a.orderPrice as currentPrice
                              from NewAck(ocFlag=1) as a unidirectional,
                              Margin#unique(exchId,symbol)  m,
                              Commission#unique(exchId,symbol)  f,
                              Instrument#unique(exchId,symbol)  i
                              where
                              (select count(*) from Position#unique(exchId,acctId,currencyId,symbol,bsFlag,hedgeFlag) as b
                              where a.exchId=b.exchId
                              and a.acctId=b.acctId
                              and a.currencyId=b.currencyId
                              and a.symbol=b.symbol
                              and a.bsFlag=b.bsFlag
                              and a.hedgeFlag=b.hedgeFlag) = 0
                              and a.exchId=m.exchId
                              and a.exchId=f.exchId
                              and a.exchId=i.exchId
                              and a.symbol=m.symbol
                              and a.symbol=f.symbol
                              and a.symbol=i.symbol;
```

**Comment by bernhardttom** [comment]
Did you recompile the EPL? Did you make sure to update all jar file versions?

**Comment by yangguang760** [comment]
@bernhardttom 
I did not notice that the compiled modules are incompatible between 8.0.0 and 8.0.0-beta1.
After re-compile all modules, now the program works well again.
Thank you.
